# Nome do projeto dbt, deve ser em letras minúsculas e underscores
name: 'dbt_learn'                 # Nome único do projeto
version: '1.0.0'                  # Versão do projeto

# Define qual "profile" dbt vai usar
profile: 'dbt_learn'              # Perfil de conexão configurado no profiles.yml

# Caminhos onde o dbt busca arquivos de diferentes tipos
model-paths: ["models"]           # Diretório de modelos
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]             # Diretório de dados estáticos (seeds)
macro-paths: ["macros"]           # Diretório de macros
snapshot-paths: ["snapshots"]     # Diretório de snapshots

clean-targets:                    # Diretórios removidos pelo comando dbt clean
  - "target"
  - "dbt_packages"

# Configurações de modelos
models:
  dbt_learn:
    # Aplicado a todos os arquivos em models/staging/
    staging:
      schema: staging             # Esquema no DW para modelos de staging
      materialized: table         # Materialização padrão desses modelos
      tags: ['staging']           # Etiquetas para facilitar organização

    intermediate:
      materialized: ephemeral     # Modelos intermediários não criam tabela/visão
      tags: ['intermediate']

    marts:
      schema: marts               # Esquema específico para modelos de marts
      materialized: table         # Materialização em tabelas
      tags: ['marts']

seeds:
  +schema: seeds                  # Esquema no DW para seeds
  tags: ['seeds']                 # Etiqueta para classificação