version: 2  # Versão do arquivo de configurações do dbt

sources:  # Lista de fontes de dados
  - name: finance  # Nome do dataset
    description: "Dados brutos do sistema financeiro da empresa"  # Descrição do dataset
    schema: data_set_financial  # Schema onde os dados estão armazenados
    loader: bigquery  # Tipo de banco de dados
    loaded_at_field: data_carga  # Campo que indica a data de carga
    meta:  # Metadados adicionais
      owner: "Vinícius"  # Proprietário do dataset
    freshness:  # Configuração de atualização
      warn_after: {count: 1, period: day}   # Emite alerta após 1 dia sem atualização
      error_after: {count: 2, period: day}  # Emite erro após 2 dias sem atualização

    tables:  # Lista de tabelas pertencentes à fonte
      - name: dados_financeiros  # Tabela com os lançamentos financeiros
        description: "Tabela com os lancamentos financeiros"  # Descrição da tabela
        columns:  # Colunas da tabela
          - name: banco
            description: "Nome do Banco"
          - name: categoria
            description: "Categoria do lancamento"
          - name: data
            description: "Data do lancamento"
          - name: destino
            description: "Destino do lancamento"
          - name: id
            description: "Identificador do lancamento"
            tests:  # Testes a serem aplicados
              - not_null # Verifica se o campo não é nulo
              - unique  # Verifica se o campo é único
          - name: mes
            description: "Mes do lancamento"
          - name: nome
            description: "Nome do lancamento"
          - name: responsavel
            description: "Responsavel pelo lancamento"
          - name: status
            description: "Status do lancamento"
          - name: tipo
            description: "Tipo do lancamento"
          - name: valor
            description: "Valor do lancamento"
          - name: valor_real
            description: "Valor real do lancamento"